[2024-04-23T16:28:08.615+0000] {processor.py:161} INFO - Started process (PID=1190) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:28:08.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:28:08.618+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:08.617+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:28:08.623+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:08.622+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:28:08.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:28:08.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.027 seconds
[2024-04-23T16:28:17.500+0000] {processor.py:161} INFO - Started process (PID=1211) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:28:17.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:28:17.504+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:17.504+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:28:17.514+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:17.512+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:28:17.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:28:17.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.040 seconds
[2024-04-23T16:28:47.811+0000] {processor.py:161} INFO - Started process (PID=1270) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:28:47.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:28:47.814+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:47.813+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:28:47.819+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:28:47.818+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:28:47.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:28:47.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.031 seconds
[2024-04-23T16:29:18.128+0000] {processor.py:161} INFO - Started process (PID=1328) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:29:18.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:29:18.132+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:29:18.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:29:18.139+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:29:18.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:29:18.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:29:18.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.036 seconds
[2024-04-23T16:29:48.402+0000] {processor.py:161} INFO - Started process (PID=1387) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:29:48.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:29:48.404+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:29:48.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:29:48.410+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:29:48.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:29:48.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:29:48.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.032 seconds
[2024-04-23T16:30:18.922+0000] {processor.py:161} INFO - Started process (PID=1446) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:30:18.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:30:18.925+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:30:18.924+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:30:18.929+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:30:18.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:30:18.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:30:18.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.035 seconds
[2024-04-23T16:30:49.282+0000] {processor.py:161} INFO - Started process (PID=1505) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:30:49.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:30:49.285+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:30:49.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:30:49.291+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:30:49.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:30:49.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:30:49.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.034 seconds
[2024-04-23T16:31:19.577+0000] {processor.py:161} INFO - Started process (PID=1564) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:31:19.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:31:19.580+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:31:19.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:31:19.586+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:31:19.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:31:19.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:31:19.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.040 seconds
[2024-04-23T16:31:49.809+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:31:49.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:31:49.812+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:31:49.812+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:31:49.819+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:31:49.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:31:49.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:31:49.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.036 seconds
[2024-04-23T16:32:19.960+0000] {processor.py:161} INFO - Started process (PID=1682) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:32:19.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:32:19.963+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:32:19.963+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:32:19.968+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:32:19.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:32:19.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:32:19.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.032 seconds
[2024-04-23T16:32:50.109+0000] {processor.py:161} INFO - Started process (PID=1740) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:32:50.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:32:50.112+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:32:50.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:32:50.116+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:32:50.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:32:50.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:32:50.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.026 seconds
[2024-04-23T16:33:20.263+0000] {processor.py:161} INFO - Started process (PID=1799) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:33:20.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:33:20.266+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:33:20.266+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:33:20.271+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:33:20.269+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:33:20.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:33:20.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.029 seconds
[2024-04-23T16:33:51.125+0000] {processor.py:161} INFO - Started process (PID=1858) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:33:51.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:33:51.128+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:33:51.128+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:33:51.135+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:33:51.133+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:33:51.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:33:51.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.036 seconds
[2024-04-23T16:34:21.503+0000] {processor.py:161} INFO - Started process (PID=1917) to work on /opt/airflow/dags/hw.py
[2024-04-23T16:34:21.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw.py for tasks to queue
[2024-04-23T16:34:21.505+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:34:21.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw.py
[2024-04-23T16:34:21.510+0000] {logging_mixin.py:188} INFO - [2024-04-23T16:34:21.508+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-04-23T16:34:21.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw.py
[2024-04-23T16:34:21.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw.py took 0.025 seconds
